version: "3.9"

services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-product-api-app}:${IMAGE_TAG:-latest}
    container_name: product-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
